name: Auto Update Dependencies

on:
  push:
    branches:
      - main  # Change to your branch if needed
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Change to your Python version

      - name: Install dependencies and update requirements.txt
        run: |
          chmod +x auto_update_requirements.sh
          ./auto_update_requirements.sh

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add requirements.txt
          git commit -m "🔄 Auto-updated dependencies" || echo "No changes to commit"
          git push
